# Generated by Django 4.1.7 on 2023-03-15 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="slug",
        ),
    ]
