# Generated by Django 4.1.7 on 2023-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_remove_item_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="image",
            new_name="image1",
        ),
        migrations.AddField(
            model_name="item",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="item/%Y/%M"),
        ),
        migrations.AddField(
            model_name="item",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="item/%Y/%M"),
        ),
    ]
