# Generated by Django 4.1.7 on 2023-03-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_rename_image_item_image1_item_image2_item_image3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="biding_end_date",
            field=models.DateField(),
        ),
    ]
