# Generated by Django 4.1.7 on 2023-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0005_alter_item_biding_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="item/%Y/%M"),
        ),
    ]
