# Generated by Django 4.1.7 on 2023-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0006_alter_item_image1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image1",
            field=models.ImageField(upload_to="item/%Y/%M"),
        ),
    ]
