# Generated by Django 4.1.7 on 2023-03-22 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0008_item_auction_status_item_potential_buyer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="payment_information",
        ),
        migrations.RemoveField(
            model_name="item",
            name="shipping_information",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Shiping",
        ),
    ]
