# Generated by Django 4.1.7 on 2023-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0009_remove_item_payment_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image1",
            field=models.ImageField(upload_to=""),
        ),
    ]
