# Generated by Django 4.1.7 on 2023-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0014_alter_item_image1_alter_item_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image1",
            field=models.ImageField(max_length=500, upload_to=None),
        ),
        migrations.AlterField(
            model_name="item",
            name="image2",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to=None
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image3",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to=None
            ),
        ),
    ]
